#!/usr/bin/with-contenv bashio
# ==============================================================================
# Generates /etc/telemt/telemt.toml from add-on options.
# ==============================================================================
set -e

CONFIG="/etc/telemt/telemt.toml"
DECOY_DIR="/data/public"
SECRET_FILE="/data/secret"
STATE_FILE="/data/state.env"
LISTEN_PORT=18080

mkdir -p "$(dirname "${CONFIG}")" "${DECOY_DIR}"

bashio::config.require 'host'
HOST=$(bashio::config 'host')

# ----- secret: option > persisted > generated -----
if bashio::config.has_value 'secret'; then
    SECRET=$(bashio::config 'secret' | tr '[:upper:]' '[:lower:]')
elif [[ -s "${SECRET_FILE}" ]]; then
    SECRET=$(cat "${SECRET_FILE}")
else
    SECRET=$(openssl rand -hex 16)
    bashio::log.info "Generated a new WEB secret."
fi
echo "${SECRET}" > "${SECRET_FILE}"
chmod 600 "${SECRET_FILE}"

# ----- public address: must be the real public IP of the TLS endpoint -----
if bashio::config.has_value 'public_ip'; then
    PUBLIC_IP=$(bashio::config 'public_ip')
else
    PUBLIC_IP=$(curl -4 -fsS --max-time 10 https://api.ipify.org || true)
    if ! bashio::var.has_value "${PUBLIC_IP}"; then
        bashio::log.fatal "Could not detect the public IP. Set the 'public_ip' option."
        bashio::exit.nok
    fi
    bashio::log.info "Detected public IP: ${PUBLIC_IP}"
fi

# ----- decoy site shown to anything that is not a valid carrier request -----
if bashio::config.has_value 'decoy_upstream'; then
    bashio::log.info "Decoy: proxying ordinary requests to $(bashio::config 'decoy_upstream')."
elif bashio::config.has_value 'decoy_html'; then
    bashio::config 'decoy_html' > "${DECOY_DIR}/index.html"
elif [[ ! -s "${DECOY_DIR}/index.html" ]]; then
    cat > "${DECOY_DIR}/index.html" <<'HTML'
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Welcome</title>
</head>
<body>
<h1>Welcome</h1>
<p>It works.</p>
</body>
</html>
HTML
fi

# ----- telemt.toml -----
{
    echo "# Auto-generated by the ha-telemt add-on. Do not edit by hand."
    echo ""
    echo "[general]"
    echo "log_level = \"$(bashio::config 'log_level')\""
    echo ""
    echo "[general.links]"
    echo "show = [\"web-user\"]"
    echo ""
    echo "[access.users]"
    echo "web-user = \"${SECRET}\""
    echo ""
    echo "[[server.listeners]]"
    echo "ip = \"0.0.0.0\""
    echo "port = ${LISTEN_PORT}"
    echo "transport = \"web\""
    echo "proxy_protocol = false"
    echo "reuse_allow = false"
    echo "web_client_ip_source = \"x_forwarded_for\""
    printf 'web_trusted_proxy_cidrs = ['
    sep=""
    for index in $(bashio::config 'trusted_proxy_cidrs|keys'); do
        printf '%s"%s"' "${sep}" "$(bashio::config "trusted_proxy_cidrs[${index}]")"
        sep=", "
    done
    printf ']\n'
    echo ""
    echo "[web]"
    echo "enabled = true"
    echo "carrier = \"$(bashio::config 'carrier')\""
    echo ""
    echo "[[web.vhosts]]"
    echo "host = \"${HOST}\""
    echo "public_addr = \"${PUBLIC_IP}:443\""
    echo ""
    echo "[web.vhosts.decoy]"
    if bashio::config.has_value 'decoy_upstream'; then
        echo "mode = \"http_upstream\""
        echo "upstream = \"http://$(bashio::config 'decoy_upstream')\""
    else
        echo "mode = \"static_directory\""
        echo "directory = \"${DECOY_DIR}\""
        echo "index = \"index.html\""
    fi
    echo ""
    echo "[[web.vhosts.profiles]]"
    echo "user = \"web-user\""
    echo "secret_mode = \"dd\""
    echo "max_sessions = 8"
    echo "max_streams = 512"
    echo "max_streams_per_session = 64"

    if bashio::config.has_value 'socks5_upstream'; then
        echo ""
        echo "[[upstreams]]"
        echo "type = \"socks5\""
        echo "address = \"$(bashio::config 'socks5_upstream')\""
        echo "weight = 1"
        echo "enabled = true"
    fi
} > "${CONFIG}"

{
    echo "HOST=${HOST}"
    echo "SECRET=${SECRET}"
    echo "PUBLIC_IP=${PUBLIC_IP}"
} > "${STATE_FILE}"

bashio::log.info "Generated ${CONFIG} for ${HOST} (${PUBLIC_IP}:443)."
